### ISSUE TITLE
Please let us know doesn't work

### ISSUE THREAD

**Issue by coffeemade** [OfficeDev/office-dev-program-docs#112]
Think we're missing your development activity? Please [let us know](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR9Kwcf15u95EqS7NUgPuo5xUNkxDRVM5RDRRTjBEMEI3QVFXUE1CWE9XMy4u). clicking on the link returns a form couldn't be found. I have a tenant muvenbar.com that is expired and I opened a ticket and need assistance as I'm actively developing in it. 
<img width="1440" alt="Screen Shot 2022-08-07 at 9 16 37 AM" src="https://user-images.githubusercontent.com/39417823/183292962-93e5d0d7-e43f-40f8-b562-52b8c07171d9.png">

**Comment by Lauragra** [comment]
Thanks for your feedback. This issue has been resolved on the site so I'll close this issue.
