### ISSUE TITLE
Account and profile deleted - Developer subscription still needed and actively beeing used

### ISSUE THREAD

**Issue by wbach82** [OfficeDev/office-dev-program-docs#113]
If the formerly used account which created the E5 subscription got deleted will the subscription still be renewed? i signed up for the developer program two years ago and i use it nearly every day. Can the profile be migrated to a new account? My work account was migrated to a new tenant. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/41477614/186860515-22a48561-67f3-48ce-b88e-a233afff47d3.png">

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and hope they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
