### ISSUE TITLE
Tracking development activity

### ISSUE THREAD

**Issue by lekejo** [OfficeDev/office-dev-program-docs#155]
Hello, the Developer Program FAQ mentions the following "For more information about the types of activities that we track, see the [terms of use](https://learn.microsoft.com/en-us/office/developer-program/terms-and-conditions)."

However, the terms of use does not seem to mention which development activity in particular are being tracked. Microsoft has somewhat left us on the hook here.

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and hope they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
