### ISSUE TITLE
We can't continue with the signup process for the following reason:  Your phone number did not pass security checks. 

### ISSUE THREAD

**Issue by varma59** [OfficeDev/office-dev-program-docs#157]
MS-CorrelationId: 00000000-7880-4cdb-8134-93a2ee31dd04  Code: 40315

**Comment by ramomkvl** [comment]
i have the same error

**Comment by Mbillel** [comment]
same for me!!!!

We can't continue with the signup process for the following reason:

Your phone number did not pass security checks.
MS-CorrelationId: 00000000-8323-4b19-8aa7-31d1172a6769

Code: 40315

**Comment by Ranaxl693** [comment]
Same issue

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and hope they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
