### ISSUE TITLE
Microsoft 365 E5 subscription error

### ISSUE THREAD

**Issue by ramomkvl** [OfficeDev/office-dev-program-docs#160]
We can't continue with the signup process for the following reason: Your phone number did not pass security checks

**Comment by hhieuminh** [comment]
I think you should wait for a day,I tried and it works

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and hope they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
