### ISSUE TITLE
Error at step Set up a Microsoft 365 developer subscription

### ISSUE THREAD

**Issue by pinkshell005** [OfficeDev/office-dev-program-docs#166]
I am facing the issue on Set up a Microsoft 365 developer subscription

when i am put the phone number then below error is appearing. i have put the different phone number but the error is coming still same.

![Capture](https://github.com/OfficeDev/office-dev-program-docs/assets/156329980/73a89b5d-5bcf-46df-a736-961ac9ab2056)

Please help me how i can resolve this.

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and hope they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
