### ISSUE TITLE
Hi @a-priestley I'm checking into this with my team.

### ISSUE THREAD

**Issue by hardyalsingh28** [OfficeDev/office-dev-program-docs#167]
I am facing same issue with one of account

We can't continue with the signup process for the following reason:

Your phone number did not pass security checks.
MS-CorrelationId: 00000000-98dd-4f28-b972-65eb19313921

Code: 40315

I tried with 4 different numbers but it's still showing the same error "Your phone number did not pass security checks".
![Capture1](https://user-images.githubusercontent.com/46337812/296418796-7322584e-15a9-4b60-8973-18c177a1cd7b.PNG)

Above is the error please check and provide the solution for that

**Comment by spidy2356** [comment]
i'm facing the same issue. any solution?????....why is it says that even if we use our personal phone number

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and hope they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
