### ISSUE TITLE
Error at step Set up a Microsoft 365 developer subscription  says phone number didnt pass security check

### ISSUE THREAD

**Issue by abhisharma97** [OfficeDev/office-dev-program-docs#168]
At the step Set up a Microsoft 365 developer account,  after I filled username, domain, and password, there was 1 more step that asked for my phone number. I inputted my phone number got an error saying phone number didnt pass security check. Code - 40315 (Screenshot below)
I was stuck at this step.
Do you have any suggestion for this?

![Error 40315](https://github.com/OfficeDev/office-dev-program-docs/assets/71059570/89522c4f-35e4-4415-b099-652a247a9f4b)

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and hope they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
