### ISSUE TITLE
Error at step Set up a Microsoft 365 developer subscription from personal account

### ISSUE THREAD

**Issue by Ranaxl693** [OfficeDev/office-dev-program-docs#169]
We can't continue with the signup process for the following reasons:

Your phone number did not pass security checks.
MS-CorrelationId: 00000000-3db7-4ec8-bc5f-b5379cb6af8a

Code: 40315

**Above is the error while setting up the developer account, please provide the solution. if have anyone? And this is my independent account.**

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and hope they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
