### ISSUE TITLE
error while setting up E5 subscription 

### ISSUE THREAD

**Issue by cadalt0** [OfficeDev/office-dev-program-docs#170]
We can't continue with the signup process for the following reason:

Your phone number did not pass security checks.
MS-CorrelationId: 00000000-2c86-4f60-bdc4-994f046760dd

Code: 40315

facing this use please help 
![image](https://github.com/OfficeDev/office-dev-program-docs/assets/67013305/c11ab1a4-17ec-435d-a6c3-611bc0beefa2) 

(I have removed phone no while taking screenshot)

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and hope they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
