### ISSUE TITLE
Error while verifing the mobile no. in E5 Subscription 

### ISSUE THREAD

**Issue by PradumnKadam** [OfficeDev/office-dev-program-docs#171]
We can't continue with the signup process for the following reason:

Your phone number did not pass security checks.
MS-CorrelationId: 00000000-382b-45d4-a572-bdd6173e63d2

Code: 40315

Can u help with this issue

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
