### ISSUE TITLE
Unable to verify new developer MS 365 E5 subscription

### ISSUE THREAD

**Issue by laage** [OfficeDev/office-dev-program-docs#174]
As many others here I have a problem verifying a new developer account using a Swedish phone number.
I've tested a couple of numbers but none of them work, but give the same error.

Error code is:
```
We can't continue with the signup process for the following reason:

Your phone number did not pass security checks.
MS-CorrelationId: 00000000-028d-4a70-962f-4a1769902061

Code: 40301
```
![image](https://github.com/OfficeDev/office-dev-program-docs/assets/15277889/1512f465-c415-47af-bd4b-21a6d5f79d62)

**Comment by orvpagadua** [comment]
same....  called the support, didnt find a thing.

**Comment by fnxln** [comment]
same, support is useless...

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and hope they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
