### ISSUE TITLE
Unable to create new subscription

### ISSUE THREAD

**Issue by chrisn1992** [OfficeDev/office-dev-program-docs#190]
Deleted my two subscription sandboxes to test on fresh sandbox, turned out I cannot create the third sandbox while the oldest(2 years ago) and the recently deleted sandbox are still there even it said "Deleted subscription". I thought old subscription will be removed after 60 days and the tenant will be available to pickup later.

**Comment by lindalu-MSFT** [comment]
Hi, sorry to hear you were having issues and they're resolved now! I'm closing this issue; if you still need assistance, contact [M365DevXSiteTeam@microsoft.com](mailto:M365DevXSiteTeam@microsoft.com). As you can see, this repo isn't monitored regularly. We're working on that!
