### ISSUE TITLE
Unable to sign into Dev Center

### ISSUE THREAD

**Issue by david-vinje** [OfficeDev/office-dev-program-docs#218]
https://developer.microsoft.com/en-us/microsoft-365

It's just a div without any functionality. 

<img width="1002" alt="Screenshot 2024-09-18 at 10 19 54" src="https://github.com/user-attachments/assets/8d0ae082-bbf0-43f2-acda-cf31d6ea6ae1">

**Comment by lindalu-MSFT** [comment]
I believe this issue has been resolved. If you're still experiencing this, kindly reopen issue and tag me. The top image is "by design", the links all work and go to content. Thanks, Linda
