### ISSUE TITLE
Mismatch in included licenses listing and reality

### ISSUE THREAD

**Issue by ross-bohr** [OfficeDev/office-dev-program-docs#43]
There is a mismatch between what's listed on the "Office 365 Developer Program FAQ" page, section "What's included in the Office 365 developer subscription?" and reality.

After activating the "Office 365 Developer Program" (as an included benefit to an existing Visual Studio Enterprise subscription), the Admin Portal (https://portal.office.com/AdminPortal/Home#/users) shows only "Flow Free" and "Flow for Office 365" license plans, i.e. - **not** showing the "Flow for Office **Plan 2**" that is listed in the aforementioned documentation page.

There's either an issue in the documentation or in the Admin Portal for Office 365 Developer Program.

**Comment by Lauragra** [comment]
Thanks for your feedback. We just updated the topic to reflect what's included in the subscription. The update should be published live shortly.
