### ISSUE TITLE
My renewable subscription is only renewed for one day?

### ISSUE THREAD

**Issue by landall** [OfficeDev/office-dev-program-docs#50]
The document says it will be renewed for another 90 days.
But my account was renewed twice. once for another 60 days and once for another one day.
Is is a bug or a document error?

**Comment by Lauragra** [comment]
Hi, thanks for asking. Can you let us know your subscription domain name, so that we can investigate?

**Comment by landall** [comment]
lolitaup.onmicrosoft.com

**Comment by Lauragra** [comment]
Hi, thanks for the information, we are investigating and we will get back to you soon.

**Comment by landall** [comment]
Is there any solution?

**Comment by Lauragra** [comment]
Hi, yes, we found a bug in our logic and we're looking into fixing it now. We will be able to extend your subscription beyond the 1 day. Thanks.

**Comment by landall** [comment]
> Hi, yes, we found a bug in our logic and we're looking into fixing it now. We will be able to extend your subscription beyond the 1 day. Thanks.

Glad to hear this news. For our testing plan needs about 10-20 days to run a round, it is helpful to me. 

Besides, is it correct to get an extra 60 days, not 90 days, when the subscription is renewed?

**Comment by Lauragra** [comment]
The renewal is for 90 days from the day that the subscription expired. We'll make sure that this is clarified in the docs.

**Comment by Lauragra** [comment]
Your subscription should be renewed now for another 90 days. I'm going to close this issue, but feel free to reopen if you have further problems. Thanks.

**Comment by landall** [comment]
thanks for your help!
