### ISSUE TITLE
It takes too much time to install user pack

### ISSUE THREAD

**Issue by thechiefalone** [OfficeDev/office-dev-program-docs#65]
I am trying to install sample user pack but it always spinning. 

![image](https://user-images.githubusercontent.com/3797372/85393241-f6bdd780-b54c-11ea-9abb-2acf58ec9b99.png)

However I can see the installed sample users from my admin dashboard. 

![image](https://user-images.githubusercontent.com/3797372/85393362-253bb280-b54d-11ea-9064-81924f315ab4.png)

This is my second try and in my first try I waited more than 1 day. Nothing changed, just spinning and i can not install events sample pack.

**Comment by Lauragra** [comment]
Hi, did anything change for you after you refreshed the page? It looks like you were able to successfully install the sample pack.

**Comment by Lauragra** [comment]
The User content pack makes sure that the tenant is fully provisioned and, in some situations, it can take several hours while it's waiting for tenant provisioning.

**Comment by thechiefalone** [comment]
Yes, I have been waiting since yesterday, and Now I see it came with an error and reinstalling it. Differently, microsoft asked for mobile number for my trial admin account ( thechiefalone@alperendev.onmicrosoft.com )and I gave it. Let's see the result. 

![image](https://user-images.githubusercontent.com/3797372/85526752-8ecdc680-b60a-11ea-8607-e9b7e0498edb.png)

**Comment by thechiefalone** [comment]
New update, I got the error again after one day , 

![image](https://user-images.githubusercontent.com/3797372/85713765-00307680-b6ea-11ea-9998-8941a5807c7c.png)

I am getting this error , an internal server error but still I have users on my admin panel. 

![image](https://user-images.githubusercontent.com/3797372/85713879-23f3bc80-b6ea-11ea-9825-7e4b5f42425c.png)

**Comment by Lauragra** [comment]
We are seeing high usage and your tenant may be taking longer to fully provision. Please retry and let us know if it fails again. Thanks.

**Comment by thechiefalone** [comment]
Yes it is failed again :(

**Comment by thechiefalone** [comment]
> We are seeing high usage and your tenant may be taking longer to fully provision. Please retry and let us know if it fails again. Thanks.

Yes it is failed again and I will try one more time for the weekend.

**Comment by Lauragra** [comment]
Thanks for the screenshot, this helps our engineering team investigate the issue. It looks like the SharePoint and OneDrive part of the tenant is not fully provisioned.

Please try signing in to OneDrive as user Pattif or accessing SharePoint sites. If that works, you can try again to install the user content pack. Otherwise, you'll need to wait some more time for it to provision. We can also escalate the issue to the SharePoint tenant provisioning team, if the tenant is not fully provisioned in a week.

**Comment by thechiefalone** [comment]
![image](https://user-images.githubusercontent.com/3797372/86059776-b89c4880-ba63-11ea-8722-6c187503036a.png)

Unfortunately doesn't work. Normally This user has access to applications. 

![image](https://user-images.githubusercontent.com/3797372/86059945-14ff6800-ba64-11ea-8dda-098e403af5e5.png)

![image](https://user-images.githubusercontent.com/3797372/86060011-306a7300-ba64-11ea-9a22-a2292a6d01e9.png)

**Comment by thechiefalone** [comment]
@Lauragra my problem is still exist and really I can not find anyone to help me.

**Comment by Lauragra** [comment]
@thechiefalone , we've filed an incident internally with the SharePoint and OneDrive team. We'll update you when it's resolved. Thanks.
